modLoader="javafml" #mandatory

loaderVersion="[30,)" #mandatory (24 is current forge version)

credits="Thanks to Udemy for great Java courses." #optional

authors="kwpugh" #optional

[[mods]] #mandatory
modId="veggie_way" #mandatory
version="2.1.13" #mandatory
displayName="The Veggie Way" #mandatory
description='''
The veggie way to nutritious food without killing
'''


[[dependencies.veggie_way]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[30,)" #mandatory
    ordering="NONE"
    side="BOTH"


# Here's another dependency
[[dependencies.veggie_way]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.1, 1.15.2]"
    ordering="NONE"
    side="BOTH"
